name: realtime-chat-app

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - realtime-chat-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: >
      redis-server 
      --requirepass
      --appendonly
    volumes:
      - redis_data:/data
    networks:
      - realtime-chat-network

volumes:
  postgres_data:
  redis_data:

networks:
  realtime-chat-network:
    driver: bridge
