name: realtime-chat-app

services:
  app:
    build:
      context: .
      dockerfile: apps/app/Dockerfile
      args:
        VITE_BASE_HTTP_URL:
        VITE_BASE_WS_URL:
    container_name: app
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - realtime-chat-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: server
    env_file:
      - apps/server/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    networks:
      - realtime-chat-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - realtime-chat-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: >
      redis-server 
      --requirepass
      --appendonly
    volumes:
      - redis_data:/data
    networks:
      - realtime-chat-network

volumes:
  postgres_data:
  redis_data:

networks:
  realtime-chat-network:
    driver: bridge
